name: iOS CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ios-ci:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Fastlane CI
        run: bundle exec fastlane ci
